server:
  port: 8088
  servlet:
    context-path: /admin
  undertow:
    buffer-size: 1024
    io-threads: 1
    worker-threads: 4
    direct-buffers: true

spring:
  profiles:
    active: test
  thymeleaf:
    cache: false
  application:
    name: andrei-admin
  session:
    redis:
      namespace: andrei
      flush-mode: immediate
  kafka:
    bootstrap-servers: 45.32.49.109:9092
    consumer:
      group-id: andrei
      enable-auto-commit: false
      auto-commit-interval: 100ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 15000
    producer:
      retries: 2
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 1


mybatis:
  mapper-locations: classpath:mybatis/andrei/*.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  identity: MYSQL
  not-empty: true
  mappers:
    - com.telfa.andrei.base.BaseMapper


---
spring:
  profiles: test
  ## datasource config, use alibaba druid datasource connector
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/andrei?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      maxActive: 20
      initialSize: 3
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout:
    jedis:
      pool:
        max-idle: 20
        min-idle: 8
        max-wait: 10000ms
  session:
    store-type: redis
